// Auto-generated by VibeStack — redirects to first entity page
import { createFileRoute, redirect } from '@tanstack/react-router'

export const Route = createFileRoute('/')({
  beforeLoad: () => {
    throw redirect({ to: '/menu-categories' })
  },
})
