// Auto-generated by VibeStack Design Engine v2 — CardGrid skill
import { useState } from 'react'
import { createFileRoute, Link } from '@tanstack/react-router'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { supabase } from '@/lib/supabase'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Plus, Trash2 } from 'lucide-react'

export const Route = createFileRoute('/_authenticated/menu-categories')({
  component: MenuCategoriesListPage,
})

function MenuCategoriesListPage() {
  const queryClient = useQueryClient()
  const [open, setOpen] = useState(false)
  const [form, setForm] = useState<Record<string, string | number | boolean>>({})

  const { data: items = [], isPending, error } = useQuery({
    queryKey: ['menu_categories'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('menu_categories')
        .select('*')
        .order('created_at', { ascending: false })
      if (error) throw error
      return data ?? []
    },
  })

  const createMenuCategories = useMutation({
    mutationFn: async (values: Record<string, unknown>) => {
      const { error } = await supabase.from('menu_categories').insert(values)
      if (error) throw error
    },
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['menu_categories'] }); setOpen(false); setForm({}) },
  })

  const deleteMenuCategories = useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase.from('menu_categories').delete().eq('id', id)
      if (error) throw error
    },
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['menu_categories'] }),
  })



  if (isPending) return <div className="flex justify-center py-20"><p className="text-muted-foreground">Loading menu categories...</p></div>
  if (error) return <div className="flex justify-center py-20"><p className="text-destructive">Error: {error.message}</p></div>

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-3xl font-bold tracking-tight">Menu Categories</h1>
        <Dialog open={open} onOpenChange={setOpen}>
          <DialogTrigger asChild>
            <Button><Plus className="mr-2 h-4 w-4" />New Menu Category</Button>
          </DialogTrigger>
          <DialogContent className="sm:max-w-[500px]">
            <DialogHeader>
              <DialogTitle>New Menu Category</DialogTitle>
              <DialogDescription className="sr-only">Create a new Menu Category</DialogDescription>
            </DialogHeader>
            <form className="space-y-4" onSubmit={e => { e.preventDefault(); createMenuCategories.mutate(form) }}>
          <div>
            <label className="text-sm font-medium">Name</label>
            <Input type="text" value={String(form.name ?? '')} onChange={e => setForm(p => ({ ...p, name: e.target.value }))} placeholder="Enter name" />
          </div>
          <div>
            <label className="text-sm font-medium">Description</label>
            <Textarea value={String(form.description ?? '')} onChange={e => setForm(p => ({ ...p, description: e.target.value }))} placeholder="Enter description" />
          </div>
          <div>
            <label className="text-sm font-medium">Display Order</label>
            <Input type="number" value={String(form.display_order ?? '')} onChange={e => setForm(p => ({ ...p, display_order: e.target.value }))} placeholder="Enter display order" />
          </div>
          <div>
            <label className="text-sm font-medium">Active</label>
            <Input type="text" value={String(form.active ?? '')} onChange={e => setForm(p => ({ ...p, active: e.target.value }))} placeholder="" />
          </div>
          <div>
            <label className="text-sm font-medium">Created By</label>
            <Input type="text" value={String(form.created_by ?? '')} onChange={e => setForm(p => ({ ...p, created_by: e.target.value }))} placeholder="Enter created by" />
          </div>
              <Button type="submit" disabled={createMenuCategories.isPending} className="w-full">
                {createMenuCategories.isPending ? 'Creating...' : 'Create Menu Category'}
              </Button>
            </form>
          </DialogContent>
        </Dialog>
      </div>

      {items.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-20 text-center">
          <p className="text-muted-foreground mb-4">No menu categories yet. Create your first menu categories!</p>
          <Button onClick={() => setOpen(true)}><Plus className="mr-2 h-4 w-4" />Add your first menu category</Button>
        </div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {items.map((item: Record<string, unknown>) => (
            <Card key={String(item.id)} className="overflow-hidden hover:shadow-lg transition-shadow group">
              <div className="aspect-video bg-gradient-to-br from-primary/20 to-primary/5 flex items-center justify-center">
                <span className="text-4xl font-bold text-primary/30">{String(item.name ?? '').charAt(0).toUpperCase()}</span>
              </div>
              <CardHeader className="pb-2">
                <CardTitle className="text-lg line-clamp-2">
                  <Link to="/menu-categories/$id" params={{ id: String(item.id) }} className="hover:text-primary transition-colors">
                    {String(item.name ?? 'Untitled')}
                  </Link>
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-1">
              <p className="text-sm text-muted-foreground">{String(item.active ?? '—')}</p>
              <p className="text-sm text-muted-foreground">{String(item.display_order ?? '—')}</p>
                <div className="pt-2 flex justify-end">
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={e => { e.preventDefault(); deleteMenuCategories.mutate(String(item.id)) }}
                    className="text-destructive hover:text-destructive"
                  >
                    <Trash2 className="h-4 w-4" />
                  </Button>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  )
}
