// Auto-generated by VibeStack Design Engine v2 — MenuGrid skill
import { useState } from 'react'
import { createFileRoute, Link } from '@tanstack/react-router'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { supabase } from '@/lib/supabase'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Plus, Trash2 } from 'lucide-react'

export const Route = createFileRoute('/_authenticated/menu-items')({
  component: MenuItemsMenuPage,
})

function MenuItemsMenuPage() {
  const queryClient = useQueryClient()
  const [open, setOpen] = useState(false)
  const [form, setForm] = useState<Record<string, string | number | boolean>>({})

  const { data: items = [], isPending, error } = useQuery({
    queryKey: ['menu_items'],
    queryFn: async () => {
      const { data, error } = await supabase.from('menu_items').select('*').order('created_at', { ascending: false })
      if (error) throw error
      return data ?? []
    },
  })

  const createMenuItems = useMutation({
    mutationFn: async (values: Record<string, unknown>) => {
      const { error } = await supabase.from('menu_items').insert(values)
      if (error) throw error
    },
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['menu_items'] }); setOpen(false); setForm({}) },
  })



  const deleteMenuItems = useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase.from('menu_items').delete().eq('id', id)
      if (error) throw error
    },
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['menu_items'] }),
  })

  if (isPending) return <div className="flex justify-center py-20"><p className="text-muted-foreground">Loading menu...</p></div>
  if (error) return <div className="flex justify-center py-20"><p className="text-destructive">Error: {error.message}</p></div>

  return (
    <div className="space-y-6 max-w-4xl mx-auto">
      <div className="flex items-center justify-between border-b pb-4">
        <h1 className="text-3xl font-bold tracking-tight">Menu Items</h1>
        <Dialog open={open} onOpenChange={setOpen}>
          <DialogTrigger asChild>
            <Button><Plus className="mr-2 h-4 w-4" />Add Item</Button>
          </DialogTrigger>
          <DialogContent>
            <DialogHeader><DialogTitle>New Menu Item</DialogTitle><DialogDescription className="sr-only">Create a new Menu Item</DialogDescription></DialogHeader>
            <form className="space-y-4" onSubmit={e => { e.preventDefault(); createMenuItems.mutate(form) }}>
          <div><label className="text-sm font-medium">Category Id</label><Input type="text" value={String(form.category_id ?? '')} onChange={e => setForm(p => ({ ...p, category_id: e.target.value }))} placeholder="Enter category id" /></div>
          <div><label className="text-sm font-medium">Name</label><Input type="text" value={String(form.name ?? '')} onChange={e => setForm(p => ({ ...p, name: e.target.value }))} placeholder="Enter name" /></div>
          <div><label className="text-sm font-medium">Description</label><Textarea value={String(form.description ?? '')} onChange={e => setForm(p => ({ ...p, description: e.target.value }))} placeholder="Enter description" /></div>
          <div><label className="text-sm font-medium">Price</label><Input type="number" value={String(form.price ?? '')} onChange={e => setForm(p => ({ ...p, price: e.target.value }))} placeholder="Enter price" /></div>
          <div><label className="text-sm font-medium">Dietary Tags</label><Input type="text" value={String(form.dietary_tags ?? '')} onChange={e => setForm(p => ({ ...p, dietary_tags: e.target.value }))} placeholder="Enter dietary tags" /></div>
          <div><label className="text-sm font-medium">Available</label><Input type="text" value={String(form.available ?? '')} onChange={e => setForm(p => ({ ...p, available: e.target.value }))} placeholder="" /></div>
          <div><label className="text-sm font-medium">Preparation Time Minutes</label><Input type="number" value={String(form.preparation_time_minutes ?? '')} onChange={e => setForm(p => ({ ...p, preparation_time_minutes: e.target.value }))} placeholder="Enter preparation time minutes" /></div>
          <div><label className="text-sm font-medium">Image Url</label><Input type="text" value={String(form.image_url ?? '')} onChange={e => setForm(p => ({ ...p, image_url: e.target.value }))} placeholder="e.g., https://example.com" /></div>
          <div><label className="text-sm font-medium">Calories</label><Input type="number" value={String(form.calories ?? '')} onChange={e => setForm(p => ({ ...p, calories: e.target.value }))} placeholder="Enter calories" /></div>
          <div><label className="text-sm font-medium">Created By</label><Input type="text" value={String(form.created_by ?? '')} onChange={e => setForm(p => ({ ...p, created_by: e.target.value }))} placeholder="Enter created by" /></div>
              <Button type="submit" disabled={createMenuItems.isPending} className="w-full">
                {createMenuItems.isPending ? 'Adding...' : 'Add Item'}
              </Button>
            </form>
          </DialogContent>
        </Dialog>
      </div>

      {items.length === 0 ? (
        <div className="py-20 text-center">
          <p className="text-muted-foreground mb-4">No items yet. Add your first menu item.</p>
          <Button onClick={() => setOpen(true)}><Plus className="mr-2 h-4 w-4" />Add Item</Button>
        </div>
      ) : (
        <div className="divide-y">
          {items.map((item: Record<string, unknown>) => (
            <div key={String(item.id)} className="flex items-start justify-between py-4 group">
              <div className="flex-1">
                <Link to="/menu-items/$id" params={{ id: String(item.id) }} className="font-semibold text-lg hover:text-primary transition-colors">
                  {String(item.name ?? 'Untitled')}
                </Link>
                {item.description && <p className="text-sm text-muted-foreground mt-1">{String(item.description)}</p>}
              </div>
              <div className="flex items-center gap-3 ml-4">
                <span className="font-semibold text-lg">{'$'}{Number(item.price ?? 0).toFixed(2)}</span>
                <Button variant="ghost" size="sm" onClick={() => deleteMenuItems.mutate(String(item.id))} className="opacity-0 group-hover:opacity-100 text-destructive hover:text-destructive">
                  <Trash2 className="h-4 w-4" />
                </Button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
