// Auto-generated by VibeStack Design Engine v2 — ProductDetail skill
import { useState } from 'react'
import { createFileRoute, Link } from '@tanstack/react-router'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { supabase } from '@/lib/supabase'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { ArrowLeft, Edit2, X } from 'lucide-react'

export const Route = createFileRoute('/_authenticated/menu-items/$id')({
  component: MenuItemsDetailPage,
})

function MenuItemsDetailPage() {
  const { id } = Route.useParams()
  const queryClient = useQueryClient()
  const [isEditing, setIsEditing] = useState(false)
  const [editForm, setEditForm] = useState<Record<string, string | number | boolean>>({})

  const menuItems = useQuery({
    queryKey: ['menu_items', id],
    queryFn: async () => {
      const { data, error } = await supabase.from('menu_items').select('*').eq('id', id).single()
      if (error) throw error
      return data as Record<string, unknown>
    },
  })

  const updateMenuItems = useMutation({
    mutationFn: async (values: Record<string, unknown>) => {
      const { error } = await supabase.from('menu_items').update(values).eq('id', id)
      if (error) throw error
    },
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['menu_items'] }); setIsEditing(false) },
  })



  if (menuItems.isPending) return <div className="flex justify-center py-20"><p className="text-muted-foreground">Loading...</p></div>
  if (menuItems.error) return <div className="flex justify-center py-20"><p className="text-destructive">Error: {menuItems.error.message}</p></div>
  if (!menuItems.data) return <div className="flex justify-center py-20"><p className="text-muted-foreground">Not found</p></div>

  const data = menuItems.data

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Link to="/menu-items" className="flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground transition-colors">
          <ArrowLeft className="h-4 w-4" /> Back to Menu Items
        </Link>
      </div>

      {data.image_url && (
        <div className="aspect-[16/7] overflow-hidden rounded-xl">
          <img src={String(data.image_url)} alt={String(data.name ?? '')} className="w-full h-full object-cover" />
        </div>
      )}

      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">{String(data.name ?? 'Untitled')}</h1>
          {data.price && <p className="text-2xl font-semibold text-primary mt-1">{'$'}{Number(data.price).toFixed(2)}</p>}
        </div>
        <Button variant={isEditing ? 'outline' : 'default'} onClick={() => {
          if (!isEditing) setEditForm({ category_id: data.category_id ?? '', name: data.name ?? '', description: data.description ?? '', price: data.price ?? '', dietary_tags: data.dietary_tags ?? '', available: data.available ?? '', preparation_time_minutes: data.preparation_time_minutes ?? '', image_url: data.image_url ?? '', calories: data.calories ?? '', created_by: data.created_by ?? '' })
          setIsEditing(!isEditing)
        }}>
          {isEditing ? <><X className="h-4 w-4 mr-2" />Cancel</> : <><Edit2 className="h-4 w-4 mr-2" />Edit</>}
        </Button>
      </div>

      {data.description && <p className="text-muted-foreground leading-relaxed">{String(data.description)}</p>}

      {isEditing ? (
        <Card>
          <CardHeader><CardTitle>Edit Menu Item</CardTitle></CardHeader>
          <CardContent>
            <form className="space-y-4" onSubmit={e => { e.preventDefault(); updateMenuItems.mutate(editForm) }}>
              <div><label className="text-sm font-medium">Category Id</label><Input type="text" value={String(editForm.category_id ?? '')} onChange={e => setEditForm(p => ({ ...p, category_id: e.target.value }))} /></div>
              <div><label className="text-sm font-medium">Name</label><Input type="text" value={String(editForm.name ?? '')} onChange={e => setEditForm(p => ({ ...p, name: e.target.value }))} /></div>
              <div><label className="text-sm font-medium">Description</label><Textarea value={String(editForm.description ?? '')} onChange={e => setEditForm(p => ({ ...p, description: e.target.value }))} /></div>
              <div><label className="text-sm font-medium">Price</label><Input type="number" value={String(editForm.price ?? '')} onChange={e => setEditForm(p => ({ ...p, price: e.target.value }))} /></div>
              <div><label className="text-sm font-medium">Dietary Tags</label><Input type="text" value={String(editForm.dietary_tags ?? '')} onChange={e => setEditForm(p => ({ ...p, dietary_tags: e.target.value }))} /></div>
              <div><label className="text-sm font-medium">Available</label><Input type="checkbox" value={String(editForm.available ?? '')} onChange={e => setEditForm(p => ({ ...p, available: e.target.value }))} /></div>
              <div><label className="text-sm font-medium">Preparation Time Minutes</label><Input type="number" value={String(editForm.preparation_time_minutes ?? '')} onChange={e => setEditForm(p => ({ ...p, preparation_time_minutes: e.target.value }))} /></div>
              <div><label className="text-sm font-medium">Image Url</label><Input type="url" value={String(editForm.image_url ?? '')} onChange={e => setEditForm(p => ({ ...p, image_url: e.target.value }))} /></div>
              <div><label className="text-sm font-medium">Calories</label><Input type="number" value={String(editForm.calories ?? '')} onChange={e => setEditForm(p => ({ ...p, calories: e.target.value }))} /></div>
              <div><label className="text-sm font-medium">Created By</label><Input type="text" value={String(editForm.created_by ?? '')} onChange={e => setEditForm(p => ({ ...p, created_by: e.target.value }))} /></div>
              <div className="flex gap-2">
                <Button type="submit" disabled={updateMenuItems.isPending}>
                  {updateMenuItems.isPending ? 'Saving...' : 'Save'}
                </Button>
                <Button type="button" variant="outline" onClick={() => setIsEditing(false)}>Cancel</Button>
              </div>
            </form>
          </CardContent>
        </Card>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="space-y-4">
            <h3 className="font-semibold text-lg border-b pb-2">Details</h3>
            <div>
              <p className="text-sm text-muted-foreground">Category Id</p>
              <p className="font-medium">{String(data.category_id ?? '—')}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Name</p>
              <p className="font-medium">{String(data.name ?? '—')}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Description</p>
              <p className="font-medium">{String(data.description ?? '—')}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Dietary Tags</p>
              <p className="font-medium">{String(data.dietary_tags ?? '—')}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Image Url</p>
              <p className="font-medium">{String(data.image_url ?? '—')}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Created By</p>
              <p className="font-medium">{String(data.created_by ?? '—')}</p>
            </div>
          </div>
          <div className="space-y-4">
            <h3 className="font-semibold text-lg border-b pb-2">Properties</h3>
            <div>
              <p className="text-sm text-muted-foreground">Price</p>
              <p className="font-medium">{'$' + Number(data.price ?? 0).toFixed(2)}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Available</p>
              <p className="font-medium">{data.available ? 'Yes' : 'No'}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Preparation Time Minutes</p>
              <p className="font-medium">{String(data.preparation_time_minutes ?? '—')}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Calories</p>
              <p className="font-medium">{String(data.calories ?? '—')}</p>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
