// Auto-generated by VibeStack Design Engine v2 — ProductDetail skill
import { useState } from 'react'
import { createFileRoute, Link } from '@tanstack/react-router'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { supabase } from '@/lib/supabase'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { ArrowLeft, Edit2, X } from 'lucide-react'

export const Route = createFileRoute('/_authenticated/menu-categories/$id')({
  component: MenuCategoriesDetailPage,
})

function MenuCategoriesDetailPage() {
  const { id } = Route.useParams()
  const queryClient = useQueryClient()
  const [isEditing, setIsEditing] = useState(false)
  const [editForm, setEditForm] = useState<Record<string, string | number | boolean>>({})

  const menuCategories = useQuery({
    queryKey: ['menu_categories', id],
    queryFn: async () => {
      const { data, error } = await supabase.from('menu_categories').select('*').eq('id', id).single()
      if (error) throw error
      return data as Record<string, unknown>
    },
  })

  const updateMenuCategories = useMutation({
    mutationFn: async (values: Record<string, unknown>) => {
      const { error } = await supabase.from('menu_categories').update(values).eq('id', id)
      if (error) throw error
    },
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['menu_categories'] }); setIsEditing(false) },
  })



  if (menuCategories.isPending) return <div className="flex justify-center py-20"><p className="text-muted-foreground">Loading...</p></div>
  if (menuCategories.error) return <div className="flex justify-center py-20"><p className="text-destructive">Error: {menuCategories.error.message}</p></div>
  if (!menuCategories.data) return <div className="flex justify-center py-20"><p className="text-muted-foreground">Not found</p></div>

  const data = menuCategories.data

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Link to="/menu-categories" className="flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground transition-colors">
          <ArrowLeft className="h-4 w-4" /> Back to Menu Categories
        </Link>
      </div>

      <div className="aspect-[16/7] rounded-xl bg-gradient-to-br from-primary/20 to-primary/5 flex items-center justify-center">
        <span className="text-6xl font-bold text-primary/20">{String(data.name ?? '').charAt(0).toUpperCase()}</span>
      </div>

      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">{String(data.name ?? 'Untitled')}</h1>

        </div>
        <Button variant={isEditing ? 'outline' : 'default'} onClick={() => {
          if (!isEditing) setEditForm({ name: data.name ?? '', description: data.description ?? '', display_order: data.display_order ?? '', active: data.active ?? '', created_by: data.created_by ?? '' })
          setIsEditing(!isEditing)
        }}>
          {isEditing ? <><X className="h-4 w-4 mr-2" />Cancel</> : <><Edit2 className="h-4 w-4 mr-2" />Edit</>}
        </Button>
      </div>

      {data.description && <p className="text-muted-foreground leading-relaxed">{String(data.description)}</p>}

      {isEditing ? (
        <Card>
          <CardHeader><CardTitle>Edit Menu Category</CardTitle></CardHeader>
          <CardContent>
            <form className="space-y-4" onSubmit={e => { e.preventDefault(); updateMenuCategories.mutate(editForm) }}>
              <div><label className="text-sm font-medium">Name</label><Input type="text" value={String(editForm.name ?? '')} onChange={e => setEditForm(p => ({ ...p, name: e.target.value }))} /></div>
              <div><label className="text-sm font-medium">Description</label><Textarea value={String(editForm.description ?? '')} onChange={e => setEditForm(p => ({ ...p, description: e.target.value }))} /></div>
              <div><label className="text-sm font-medium">Display Order</label><Input type="number" value={String(editForm.display_order ?? '')} onChange={e => setEditForm(p => ({ ...p, display_order: e.target.value }))} /></div>
              <div><label className="text-sm font-medium">Active</label><Input type="checkbox" value={String(editForm.active ?? '')} onChange={e => setEditForm(p => ({ ...p, active: e.target.value }))} /></div>
              <div><label className="text-sm font-medium">Created By</label><Input type="text" value={String(editForm.created_by ?? '')} onChange={e => setEditForm(p => ({ ...p, created_by: e.target.value }))} /></div>
              <div className="flex gap-2">
                <Button type="submit" disabled={updateMenuCategories.isPending}>
                  {updateMenuCategories.isPending ? 'Saving...' : 'Save'}
                </Button>
                <Button type="button" variant="outline" onClick={() => setIsEditing(false)}>Cancel</Button>
              </div>
            </form>
          </CardContent>
        </Card>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="space-y-4">
            <h3 className="font-semibold text-lg border-b pb-2">Details</h3>
            <div>
              <p className="text-sm text-muted-foreground">Name</p>
              <p className="font-medium">{String(data.name ?? '—')}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Description</p>
              <p className="font-medium">{String(data.description ?? '—')}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Created By</p>
              <p className="font-medium">{String(data.created_by ?? '—')}</p>
            </div>
          </div>
          <div className="space-y-4">
            <h3 className="font-semibold text-lg border-b pb-2">Properties</h3>
            <div>
              <p className="text-sm text-muted-foreground">Display Order</p>
              <p className="font-medium">{String(data.display_order ?? '—')}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Active</p>
              <p className="font-medium">{data.active ? 'Yes' : 'No'}</p>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
