// Auto-generated by VibeStack Design Engine v2 — MenuGrid skill
import { useState } from 'react'
import { createFileRoute, Link } from '@tanstack/react-router'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { supabase } from '@/lib/supabase'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Plus, Trash2 } from 'lucide-react'

export const Route = createFileRoute('/_authenticated/order-items')({
  component: OrderItemsMenuPage,
})

function OrderItemsMenuPage() {
  const queryClient = useQueryClient()
  const [open, setOpen] = useState(false)
  const [form, setForm] = useState<Record<string, string | number | boolean>>({})

  const { data: items = [], isPending, error } = useQuery({
    queryKey: ['order_items'],
    queryFn: async () => {
      const { data, error } = await supabase.from('order_items').select('*').order('created_at', { ascending: false })
      if (error) throw error
      return data ?? []
    },
  })

  const createOrderItems = useMutation({
    mutationFn: async (values: Record<string, unknown>) => {
      const { error } = await supabase.from('order_items').insert(values)
      if (error) throw error
    },
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['order_items'] }); setOpen(false); setForm({}) },
  })



  const deleteOrderItems = useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase.from('order_items').delete().eq('id', id)
      if (error) throw error
    },
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['order_items'] }),
  })

  if (isPending) return <div className="flex justify-center py-20"><p className="text-muted-foreground">Loading menu...</p></div>
  if (error) return <div className="flex justify-center py-20"><p className="text-destructive">Error: {error.message}</p></div>

  return (
    <div className="space-y-6 max-w-4xl mx-auto">
      <div className="flex items-center justify-between border-b pb-4">
        <h1 className="text-3xl font-bold tracking-tight">Order Items</h1>
        <Dialog open={open} onOpenChange={setOpen}>
          <DialogTrigger asChild>
            <Button><Plus className="mr-2 h-4 w-4" />Add Item</Button>
          </DialogTrigger>
          <DialogContent>
            <DialogHeader><DialogTitle>New Order Item</DialogTitle><DialogDescription className="sr-only">Create a new Order Item</DialogDescription></DialogHeader>
            <form className="space-y-4" onSubmit={e => { e.preventDefault(); createOrderItems.mutate(form) }}>
          <div><label className="text-sm font-medium">Order Id</label><Input type="text" value={String(form.order_id ?? '')} onChange={e => setForm(p => ({ ...p, order_id: e.target.value }))} placeholder="Enter order id" /></div>
          <div><label className="text-sm font-medium">Menu Item Id</label><Input type="text" value={String(form.menu_item_id ?? '')} onChange={e => setForm(p => ({ ...p, menu_item_id: e.target.value }))} placeholder="Enter menu item id" /></div>
          <div><label className="text-sm font-medium">Quantity</label><Input type="number" value={String(form.quantity ?? '')} onChange={e => setForm(p => ({ ...p, quantity: e.target.value }))} placeholder="Enter quantity" /></div>
          <div><label className="text-sm font-medium">Unit Price</label><Input type="number" value={String(form.unit_price ?? '')} onChange={e => setForm(p => ({ ...p, unit_price: e.target.value }))} placeholder="Enter unit price" /></div>
          <div><label className="text-sm font-medium">Special Instructions</label><Input type="text" value={String(form.special_instructions ?? '')} onChange={e => setForm(p => ({ ...p, special_instructions: e.target.value }))} placeholder="Enter special instructions" /></div>
          <div><label className="text-sm font-medium">Status</label><Input type="text" value={String(form.status ?? '')} onChange={e => setForm(p => ({ ...p, status: e.target.value }))} placeholder="" /></div>
          <div><label className="text-sm font-medium">Created By</label><Input type="text" value={String(form.created_by ?? '')} onChange={e => setForm(p => ({ ...p, created_by: e.target.value }))} placeholder="Enter created by" /></div>
              <Button type="submit" disabled={createOrderItems.isPending} className="w-full">
                {createOrderItems.isPending ? 'Adding...' : 'Add Item'}
              </Button>
            </form>
          </DialogContent>
        </Dialog>
      </div>

      {items.length === 0 ? (
        <div className="py-20 text-center">
          <p className="text-muted-foreground mb-4">No items yet. Add your first menu item.</p>
          <Button onClick={() => setOpen(true)}><Plus className="mr-2 h-4 w-4" />Add Item</Button>
        </div>
      ) : (
        <div className="divide-y">
          {items.map((item: Record<string, unknown>) => (
            <div key={String(item.id)} className="flex items-start justify-between py-4 group">
              <div className="flex-1">
                <Link to="/order-items/$id" params={{ id: String(item.id) }} className="font-semibold text-lg hover:text-primary transition-colors">
                  {String(item.special_instructions ?? 'Untitled')}
                </Link>
                
              </div>
              <div className="flex items-center gap-3 ml-4">
                <span className="font-semibold text-lg">{'$'}{Number(item.unit_price ?? 0).toFixed(2)}</span>
                <Button variant="ghost" size="sm" onClick={() => deleteOrderItems.mutate(String(item.id))} className="opacity-0 group-hover:opacity-100 text-destructive hover:text-destructive">
                  <Trash2 className="h-4 w-4" />
                </Button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
