// Auto-generated by VibeStack Design Engine v2 — ProductDetail skill
import { useState } from 'react'
import { createFileRoute, Link } from '@tanstack/react-router'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { supabase } from '@/lib/supabase'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { ArrowLeft, Edit2, X } from 'lucide-react'

export const Route = createFileRoute('/_authenticated/order-items/$id')({
  component: OrderItemsDetailPage,
})

function OrderItemsDetailPage() {
  const { id } = Route.useParams()
  const queryClient = useQueryClient()
  const [isEditing, setIsEditing] = useState(false)
  const [editForm, setEditForm] = useState<Record<string, string | number | boolean>>({})

  const orderItems = useQuery({
    queryKey: ['order_items', id],
    queryFn: async () => {
      const { data, error } = await supabase.from('order_items').select('*').eq('id', id).single()
      if (error) throw error
      return data as Record<string, unknown>
    },
  })

  const updateOrderItems = useMutation({
    mutationFn: async (values: Record<string, unknown>) => {
      const { error } = await supabase.from('order_items').update(values).eq('id', id)
      if (error) throw error
    },
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['order_items'] }); setIsEditing(false) },
  })



  if (orderItems.isPending) return <div className="flex justify-center py-20"><p className="text-muted-foreground">Loading...</p></div>
  if (orderItems.error) return <div className="flex justify-center py-20"><p className="text-destructive">Error: {orderItems.error.message}</p></div>
  if (!orderItems.data) return <div className="flex justify-center py-20"><p className="text-muted-foreground">Not found</p></div>

  const data = orderItems.data

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Link to="/order-items" className="flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground transition-colors">
          <ArrowLeft className="h-4 w-4" /> Back to Order Items
        </Link>
      </div>

      <div className="aspect-[16/7] rounded-xl bg-gradient-to-br from-primary/20 to-primary/5 flex items-center justify-center">
        <span className="text-6xl font-bold text-primary/20">{String(data.special_instructions ?? '').charAt(0).toUpperCase()}</span>
      </div>

      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">{String(data.special_instructions ?? 'Untitled')}</h1>
          {data.unit_price && <p className="text-2xl font-semibold text-primary mt-1">{'$'}{Number(data.unit_price).toFixed(2)}</p>}
        </div>
        <Button variant={isEditing ? 'outline' : 'default'} onClick={() => {
          if (!isEditing) setEditForm({ order_id: data.order_id ?? '', menu_item_id: data.menu_item_id ?? '', quantity: data.quantity ?? '', unit_price: data.unit_price ?? '', special_instructions: data.special_instructions ?? '', status: data.status ?? '', created_by: data.created_by ?? '' })
          setIsEditing(!isEditing)
        }}>
          {isEditing ? <><X className="h-4 w-4 mr-2" />Cancel</> : <><Edit2 className="h-4 w-4 mr-2" />Edit</>}
        </Button>
      </div>



      {isEditing ? (
        <Card>
          <CardHeader><CardTitle>Edit Order Item</CardTitle></CardHeader>
          <CardContent>
            <form className="space-y-4" onSubmit={e => { e.preventDefault(); updateOrderItems.mutate(editForm) }}>
              <div><label className="text-sm font-medium">Order Id</label><Input type="text" value={String(editForm.order_id ?? '')} onChange={e => setEditForm(p => ({ ...p, order_id: e.target.value }))} /></div>
              <div><label className="text-sm font-medium">Menu Item Id</label><Input type="text" value={String(editForm.menu_item_id ?? '')} onChange={e => setEditForm(p => ({ ...p, menu_item_id: e.target.value }))} /></div>
              <div><label className="text-sm font-medium">Quantity</label><Input type="number" value={String(editForm.quantity ?? '')} onChange={e => setEditForm(p => ({ ...p, quantity: e.target.value }))} /></div>
              <div><label className="text-sm font-medium">Unit Price</label><Input type="number" value={String(editForm.unit_price ?? '')} onChange={e => setEditForm(p => ({ ...p, unit_price: e.target.value }))} /></div>
              <div><label className="text-sm font-medium">Special Instructions</label><Input type="text" value={String(editForm.special_instructions ?? '')} onChange={e => setEditForm(p => ({ ...p, special_instructions: e.target.value }))} /></div>
              <div><label className="text-sm font-medium">Status</label><Input value={String(editForm.status ?? '')} onChange={e => setEditForm(p => ({ ...p, status: e.target.value }))} /></div>
              <div><label className="text-sm font-medium">Created By</label><Input type="text" value={String(editForm.created_by ?? '')} onChange={e => setEditForm(p => ({ ...p, created_by: e.target.value }))} /></div>
              <div className="flex gap-2">
                <Button type="submit" disabled={updateOrderItems.isPending}>
                  {updateOrderItems.isPending ? 'Saving...' : 'Save'}
                </Button>
                <Button type="button" variant="outline" onClick={() => setIsEditing(false)}>Cancel</Button>
              </div>
            </form>
          </CardContent>
        </Card>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="space-y-4">
            <h3 className="font-semibold text-lg border-b pb-2">Details</h3>
            <div>
              <p className="text-sm text-muted-foreground">Order Id</p>
              <p className="font-medium">{String(data.order_id ?? '—')}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Menu Item Id</p>
              <p className="font-medium">{String(data.menu_item_id ?? '—')}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Special Instructions</p>
              <p className="font-medium">{String(data.special_instructions ?? '—')}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Created By</p>
              <p className="font-medium">{String(data.created_by ?? '—')}</p>
            </div>
          </div>
          <div className="space-y-4">
            <h3 className="font-semibold text-lg border-b pb-2">Properties</h3>
            <div>
              <p className="text-sm text-muted-foreground">Quantity</p>
              <p className="font-medium">{String(data.quantity ?? '—')}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Unit Price</p>
              <p className="font-medium">{'$' + Number(data.unit_price ?? 0).toFixed(2)}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Status</p>
              <p className="font-medium">{String(data.status ?? '—')}</p>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
