// Auto-generated by VibeStack Design Engine v2 — ProductDetail skill
import { useState } from 'react'
import { createFileRoute, Link } from '@tanstack/react-router'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { supabase } from '@/lib/supabase'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { ArrowLeft, Edit2, X } from 'lucide-react'

export const Route = createFileRoute('/_authenticated/orders/$id')({
  component: OrdersDetailPage,
})

function OrdersDetailPage() {
  const { id } = Route.useParams()
  const queryClient = useQueryClient()
  const [isEditing, setIsEditing] = useState(false)
  const [editForm, setEditForm] = useState<Record<string, string | number | boolean>>({})

  const orders = useQuery({
    queryKey: ['orders', id],
    queryFn: async () => {
      const { data, error } = await supabase.from('orders').select('*').eq('id', id).single()
      if (error) throw error
      return data as Record<string, unknown>
    },
  })

  const updateOrders = useMutation({
    mutationFn: async (values: Record<string, unknown>) => {
      const { error } = await supabase.from('orders').update(values).eq('id', id)
      if (error) throw error
    },
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['orders'] }); setIsEditing(false) },
  })



  if (orders.isPending) return <div className="flex justify-center py-20"><p className="text-muted-foreground">Loading...</p></div>
  if (orders.error) return <div className="flex justify-center py-20"><p className="text-destructive">Error: {orders.error.message}</p></div>
  if (!orders.data) return <div className="flex justify-center py-20"><p className="text-muted-foreground">Not found</p></div>

  const data = orders.data

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Link to="/orders" className="flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground transition-colors">
          <ArrowLeft className="h-4 w-4" /> Back to Orders
        </Link>
      </div>

      <div className="aspect-[16/7] rounded-xl bg-gradient-to-br from-primary/20 to-primary/5 flex items-center justify-center">
        <span className="text-6xl font-bold text-primary/20">{String(data.status ?? '').charAt(0).toUpperCase()}</span>
      </div>

      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">{String(data.status ?? 'Untitled')}</h1>

        </div>
        <Button variant={isEditing ? 'outline' : 'default'} onClick={() => {
          if (!isEditing) setEditForm({ table_id: data.table_id ?? '', reservation_id: data.reservation_id ?? '', status: data.status ?? '', total_amount: data.total_amount ?? '', notes: data.notes ?? '', ordered_at: data.ordered_at ?? '', created_by: data.created_by ?? '' })
          setIsEditing(!isEditing)
        }}>
          {isEditing ? <><X className="h-4 w-4 mr-2" />Cancel</> : <><Edit2 className="h-4 w-4 mr-2" />Edit</>}
        </Button>
      </div>

      {data.notes && <p className="text-muted-foreground leading-relaxed">{String(data.notes)}</p>}

      {isEditing ? (
        <Card>
          <CardHeader><CardTitle>Edit Order</CardTitle></CardHeader>
          <CardContent>
            <form className="space-y-4" onSubmit={e => { e.preventDefault(); updateOrders.mutate(editForm) }}>
              <div><label className="text-sm font-medium">Table Id</label><Input type="text" value={String(editForm.table_id ?? '')} onChange={e => setEditForm(p => ({ ...p, table_id: e.target.value }))} /></div>
              <div><label className="text-sm font-medium">Reservation Id</label><Input type="text" value={String(editForm.reservation_id ?? '')} onChange={e => setEditForm(p => ({ ...p, reservation_id: e.target.value }))} /></div>
              <div><label className="text-sm font-medium">Status</label><Input value={String(editForm.status ?? '')} onChange={e => setEditForm(p => ({ ...p, status: e.target.value }))} /></div>
              <div><label className="text-sm font-medium">Total Amount</label><Input type="number" value={String(editForm.total_amount ?? '')} onChange={e => setEditForm(p => ({ ...p, total_amount: e.target.value }))} /></div>
              <div><label className="text-sm font-medium">Notes</label><Textarea value={String(editForm.notes ?? '')} onChange={e => setEditForm(p => ({ ...p, notes: e.target.value }))} /></div>
              <div><label className="text-sm font-medium">Ordered At</label><Input type="date" value={String(editForm.ordered_at ?? '')} onChange={e => setEditForm(p => ({ ...p, ordered_at: e.target.value }))} /></div>
              <div><label className="text-sm font-medium">Created By</label><Input type="text" value={String(editForm.created_by ?? '')} onChange={e => setEditForm(p => ({ ...p, created_by: e.target.value }))} /></div>
              <div className="flex gap-2">
                <Button type="submit" disabled={updateOrders.isPending}>
                  {updateOrders.isPending ? 'Saving...' : 'Save'}
                </Button>
                <Button type="button" variant="outline" onClick={() => setIsEditing(false)}>Cancel</Button>
              </div>
            </form>
          </CardContent>
        </Card>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="space-y-4">
            <h3 className="font-semibold text-lg border-b pb-2">Details</h3>
            <div>
              <p className="text-sm text-muted-foreground">Table Id</p>
              <p className="font-medium">{String(data.table_id ?? '—')}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Reservation Id</p>
              <p className="font-medium">{String(data.reservation_id ?? '—')}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Notes</p>
              <p className="font-medium">{String(data.notes ?? '—')}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Created By</p>
              <p className="font-medium">{String(data.created_by ?? '—')}</p>
            </div>
          </div>
          <div className="space-y-4">
            <h3 className="font-semibold text-lg border-b pb-2">Properties</h3>
            <div>
              <p className="text-sm text-muted-foreground">Status</p>
              <p className="font-medium">{String(data.status ?? '—')}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Total Amount</p>
              <p className="font-medium">{'$' + Number(data.total_amount ?? 0).toFixed(2)}</p>
            </div>
          </div>
          <div className="space-y-4">
            <h3 className="font-semibold text-lg border-b pb-2">Dates</h3>
            <div>
              <p className="text-sm text-muted-foreground">Ordered At</p>
              <p className="font-medium">{data.ordered_at ? new Date(String(data.ordered_at)).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }) : '—'}</p>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
