// Auto-generated by VibeStack Design Engine v2 — CardGrid skill
import { useState } from 'react'
import { createFileRoute, Link } from '@tanstack/react-router'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { supabase } from '@/lib/supabase'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Plus, Trash2 } from 'lucide-react'

export const Route = createFileRoute('/_authenticated/reservations')({
  component: ReservationsListPage,
})

function ReservationsListPage() {
  const queryClient = useQueryClient()
  const [open, setOpen] = useState(false)
  const [form, setForm] = useState<Record<string, string | number | boolean>>({})

  const { data: items = [], isPending, error } = useQuery({
    queryKey: ['reservations'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('reservations')
        .select('*')
        .order('created_at', { ascending: false })
      if (error) throw error
      return data ?? []
    },
  })

  const createReservations = useMutation({
    mutationFn: async (values: Record<string, unknown>) => {
      const { error } = await supabase.from('reservations').insert(values)
      if (error) throw error
    },
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['reservations'] }); setOpen(false); setForm({}) },
  })

  const deleteReservations = useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase.from('reservations').delete().eq('id', id)
      if (error) throw error
    },
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['reservations'] }),
  })



  if (isPending) return <div className="flex justify-center py-20"><p className="text-muted-foreground">Loading reservations...</p></div>
  if (error) return <div className="flex justify-center py-20"><p className="text-destructive">Error: {error.message}</p></div>

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-3xl font-bold tracking-tight">Reservations</h1>
        <Dialog open={open} onOpenChange={setOpen}>
          <DialogTrigger asChild>
            <Button><Plus className="mr-2 h-4 w-4" />New Reservation</Button>
          </DialogTrigger>
          <DialogContent className="sm:max-w-[500px]">
            <DialogHeader>
              <DialogTitle>New Reservation</DialogTitle>
              <DialogDescription className="sr-only">Create a new Reservation</DialogDescription>
            </DialogHeader>
            <form className="space-y-4" onSubmit={e => { e.preventDefault(); createReservations.mutate(form) }}>
          <div>
            <label className="text-sm font-medium">Guest Name</label>
            <Input type="text" value={String(form.guest_name ?? '')} onChange={e => setForm(p => ({ ...p, guest_name: e.target.value }))} placeholder="Enter guest name" />
          </div>
          <div>
            <label className="text-sm font-medium">Guest Email</label>
            <Input type="text" value={String(form.guest_email ?? '')} onChange={e => setForm(p => ({ ...p, guest_email: e.target.value }))} placeholder="e.g., name@example.com" />
          </div>
          <div>
            <label className="text-sm font-medium">Guest Phone</label>
            <Input type="text" value={String(form.guest_phone ?? '')} onChange={e => setForm(p => ({ ...p, guest_phone: e.target.value }))} placeholder="e.g., (555) 000-1234" />
          </div>
          <div>
            <label className="text-sm font-medium">Table Id</label>
            <Input type="text" value={String(form.table_id ?? '')} onChange={e => setForm(p => ({ ...p, table_id: e.target.value }))} placeholder="Enter table id" />
          </div>
          <div>
            <label className="text-sm font-medium">Party Size</label>
            <Input type="number" value={String(form.party_size ?? '')} onChange={e => setForm(p => ({ ...p, party_size: e.target.value }))} placeholder="Enter party size" />
          </div>
          <div>
            <label className="text-sm font-medium">Reservation Date</label>
            <Input type="text" value={String(form.reservation_date ?? '')} onChange={e => setForm(p => ({ ...p, reservation_date: e.target.value }))} placeholder="" />
          </div>
          <div>
            <label className="text-sm font-medium">Reservation Time</label>
            <Input type="text" value={String(form.reservation_time ?? '')} onChange={e => setForm(p => ({ ...p, reservation_time: e.target.value }))} placeholder="Enter reservation time" />
          </div>
          <div>
            <label className="text-sm font-medium">Status</label>
            <select className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" value={String(form.status ?? '')} onChange={e => setForm(p => ({ ...p, status: e.target.value }))}>
              <option value="">Select...</option>
              <option value="pending">pending</option>
              <option value="active">active</option>
              <option value="completed">completed</option>
            </select>
          </div>
          <div>
            <label className="text-sm font-medium">Special Requests</label>
            <Input type="text" value={String(form.special_requests ?? '')} onChange={e => setForm(p => ({ ...p, special_requests: e.target.value }))} placeholder="Enter special requests" />
          </div>
          <div>
            <label className="text-sm font-medium">Created By</label>
            <Input type="text" value={String(form.created_by ?? '')} onChange={e => setForm(p => ({ ...p, created_by: e.target.value }))} placeholder="Enter created by" />
          </div>
              <Button type="submit" disabled={createReservations.isPending} className="w-full">
                {createReservations.isPending ? 'Creating...' : 'Create Reservation'}
              </Button>
            </form>
          </DialogContent>
        </Dialog>
      </div>

      {items.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-20 text-center">
          <p className="text-muted-foreground mb-4">No reservations yet. Create your first reservations!</p>
          <Button onClick={() => setOpen(true)}><Plus className="mr-2 h-4 w-4" />Add your first reservation</Button>
        </div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {items.map((item: Record<string, unknown>) => (
            <Card key={String(item.id)} className="overflow-hidden hover:shadow-lg transition-shadow group">
              <div className="aspect-video bg-gradient-to-br from-primary/20 to-primary/5 flex items-center justify-center">
                <span className="text-4xl font-bold text-primary/30">{String(item.guest_name ?? '').charAt(0).toUpperCase()}</span>
              </div>
              <CardHeader className="pb-2">
                <CardTitle className="text-lg line-clamp-2">
                  <Link to="/reservations/$id" params={{ id: String(item.id) }} className="hover:text-primary transition-colors">
                    {String(item.guest_name ?? 'Untitled')}
                  </Link>
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-1">
              <p className="text-sm text-muted-foreground">{String(item.guest_email ?? '—')}</p>
              <p className="text-sm text-muted-foreground">{String(item.status ?? '—')}</p>
              <p className="text-sm text-muted-foreground">{String(item.party_size ?? '—')}</p>
                <div className="pt-2 flex justify-end">
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={e => { e.preventDefault(); deleteReservations.mutate(String(item.id)) }}
                    className="text-destructive hover:text-destructive"
                  >
                    <Trash2 className="h-4 w-4" />
                  </Button>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  )
}
