// Auto-generated by VibeStack Design Engine v2 — ProductDetail skill
import { useState } from 'react'
import { createFileRoute, Link } from '@tanstack/react-router'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { supabase } from '@/lib/supabase'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { ArrowLeft, Edit2, X } from 'lucide-react'

export const Route = createFileRoute('/_authenticated/reservations/$id')({
  component: ReservationsDetailPage,
})

function ReservationsDetailPage() {
  const { id } = Route.useParams()
  const queryClient = useQueryClient()
  const [isEditing, setIsEditing] = useState(false)
  const [editForm, setEditForm] = useState<Record<string, string | number | boolean>>({})

  const reservations = useQuery({
    queryKey: ['reservations', id],
    queryFn: async () => {
      const { data, error } = await supabase.from('reservations').select('*').eq('id', id).single()
      if (error) throw error
      return data as Record<string, unknown>
    },
  })

  const updateReservations = useMutation({
    mutationFn: async (values: Record<string, unknown>) => {
      const { error } = await supabase.from('reservations').update(values).eq('id', id)
      if (error) throw error
    },
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['reservations'] }); setIsEditing(false) },
  })



  if (reservations.isPending) return <div className="flex justify-center py-20"><p className="text-muted-foreground">Loading...</p></div>
  if (reservations.error) return <div className="flex justify-center py-20"><p className="text-destructive">Error: {reservations.error.message}</p></div>
  if (!reservations.data) return <div className="flex justify-center py-20"><p className="text-muted-foreground">Not found</p></div>

  const data = reservations.data

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Link to="/reservations" className="flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground transition-colors">
          <ArrowLeft className="h-4 w-4" /> Back to Reservations
        </Link>
      </div>

      <div className="aspect-[16/7] rounded-xl bg-gradient-to-br from-primary/20 to-primary/5 flex items-center justify-center">
        <span className="text-6xl font-bold text-primary/20">{String(data.guest_name ?? '').charAt(0).toUpperCase()}</span>
      </div>

      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">{String(data.guest_name ?? 'Untitled')}</h1>

        </div>
        <Button variant={isEditing ? 'outline' : 'default'} onClick={() => {
          if (!isEditing) setEditForm({ guest_name: data.guest_name ?? '', guest_email: data.guest_email ?? '', guest_phone: data.guest_phone ?? '', table_id: data.table_id ?? '', party_size: data.party_size ?? '', reservation_date: data.reservation_date ?? '', reservation_time: data.reservation_time ?? '', status: data.status ?? '', special_requests: data.special_requests ?? '', created_by: data.created_by ?? '' })
          setIsEditing(!isEditing)
        }}>
          {isEditing ? <><X className="h-4 w-4 mr-2" />Cancel</> : <><Edit2 className="h-4 w-4 mr-2" />Edit</>}
        </Button>
      </div>



      {isEditing ? (
        <Card>
          <CardHeader><CardTitle>Edit Reservation</CardTitle></CardHeader>
          <CardContent>
            <form className="space-y-4" onSubmit={e => { e.preventDefault(); updateReservations.mutate(editForm) }}>
              <div><label className="text-sm font-medium">Guest Name</label><Input type="text" value={String(editForm.guest_name ?? '')} onChange={e => setEditForm(p => ({ ...p, guest_name: e.target.value }))} /></div>
              <div><label className="text-sm font-medium">Guest Email</label><Input type="text" value={String(editForm.guest_email ?? '')} onChange={e => setEditForm(p => ({ ...p, guest_email: e.target.value }))} /></div>
              <div><label className="text-sm font-medium">Guest Phone</label><Input type="text" value={String(editForm.guest_phone ?? '')} onChange={e => setEditForm(p => ({ ...p, guest_phone: e.target.value }))} /></div>
              <div><label className="text-sm font-medium">Table Id</label><Input type="text" value={String(editForm.table_id ?? '')} onChange={e => setEditForm(p => ({ ...p, table_id: e.target.value }))} /></div>
              <div><label className="text-sm font-medium">Party Size</label><Input type="number" value={String(editForm.party_size ?? '')} onChange={e => setEditForm(p => ({ ...p, party_size: e.target.value }))} /></div>
              <div><label className="text-sm font-medium">Reservation Date</label><Input type="date" value={String(editForm.reservation_date ?? '')} onChange={e => setEditForm(p => ({ ...p, reservation_date: e.target.value }))} /></div>
              <div><label className="text-sm font-medium">Reservation Time</label><Input type="text" value={String(editForm.reservation_time ?? '')} onChange={e => setEditForm(p => ({ ...p, reservation_time: e.target.value }))} /></div>
              <div><label className="text-sm font-medium">Status</label><Input value={String(editForm.status ?? '')} onChange={e => setEditForm(p => ({ ...p, status: e.target.value }))} /></div>
              <div><label className="text-sm font-medium">Special Requests</label><Input type="text" value={String(editForm.special_requests ?? '')} onChange={e => setEditForm(p => ({ ...p, special_requests: e.target.value }))} /></div>
              <div><label className="text-sm font-medium">Created By</label><Input type="text" value={String(editForm.created_by ?? '')} onChange={e => setEditForm(p => ({ ...p, created_by: e.target.value }))} /></div>
              <div className="flex gap-2">
                <Button type="submit" disabled={updateReservations.isPending}>
                  {updateReservations.isPending ? 'Saving...' : 'Save'}
                </Button>
                <Button type="button" variant="outline" onClick={() => setIsEditing(false)}>Cancel</Button>
              </div>
            </form>
          </CardContent>
        </Card>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="space-y-4">
            <h3 className="font-semibold text-lg border-b pb-2">Details</h3>
            <div>
              <p className="text-sm text-muted-foreground">Guest Name</p>
              <p className="font-medium">{String(data.guest_name ?? '—')}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Guest Email</p>
              <p className="font-medium">{String(data.guest_email ?? '—')}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Guest Phone</p>
              <p className="font-medium">{String(data.guest_phone ?? '—')}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Table Id</p>
              <p className="font-medium">{String(data.table_id ?? '—')}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Reservation Time</p>
              <p className="font-medium">{String(data.reservation_time ?? '—')}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Special Requests</p>
              <p className="font-medium">{String(data.special_requests ?? '—')}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Created By</p>
              <p className="font-medium">{String(data.created_by ?? '—')}</p>
            </div>
          </div>
          <div className="space-y-4">
            <h3 className="font-semibold text-lg border-b pb-2">Properties</h3>
            <div>
              <p className="text-sm text-muted-foreground">Party Size</p>
              <p className="font-medium">{String(data.party_size ?? '—')}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Status</p>
              <p className="font-medium">{String(data.status ?? '—')}</p>
            </div>
          </div>
          <div className="space-y-4">
            <h3 className="font-semibold text-lg border-b pb-2">Dates</h3>
            <div>
              <p className="text-sm text-muted-foreground">Reservation Date</p>
              <p className="font-medium">{data.reservation_date ? new Date(String(data.reservation_date)).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }) : '—'}</p>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
