// Auto-generated by VibeStack Design Engine v2 — ProductDetail skill
import { useState } from 'react'
import { createFileRoute, Link } from '@tanstack/react-router'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { supabase } from '@/lib/supabase'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { ArrowLeft, Edit2, X } from 'lucide-react'

export const Route = createFileRoute('/_authenticated/restaurant-tables/$id')({
  component: RestaurantTablesDetailPage,
})

function RestaurantTablesDetailPage() {
  const { id } = Route.useParams()
  const queryClient = useQueryClient()
  const [isEditing, setIsEditing] = useState(false)
  const [editForm, setEditForm] = useState<Record<string, string | number | boolean>>({})

  const restaurantTables = useQuery({
    queryKey: ['restaurant_tables', id],
    queryFn: async () => {
      const { data, error } = await supabase.from('restaurant_tables').select('*').eq('id', id).single()
      if (error) throw error
      return data as Record<string, unknown>
    },
  })

  const updateRestaurantTables = useMutation({
    mutationFn: async (values: Record<string, unknown>) => {
      const { error } = await supabase.from('restaurant_tables').update(values).eq('id', id)
      if (error) throw error
    },
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['restaurant_tables'] }); setIsEditing(false) },
  })



  if (restaurantTables.isPending) return <div className="flex justify-center py-20"><p className="text-muted-foreground">Loading...</p></div>
  if (restaurantTables.error) return <div className="flex justify-center py-20"><p className="text-destructive">Error: {restaurantTables.error.message}</p></div>
  if (!restaurantTables.data) return <div className="flex justify-center py-20"><p className="text-muted-foreground">Not found</p></div>

  const data = restaurantTables.data

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Link to="/restaurant-tables" className="flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground transition-colors">
          <ArrowLeft className="h-4 w-4" /> Back to Restaurant Tables
        </Link>
      </div>

      <div className="aspect-[16/7] rounded-xl bg-gradient-to-br from-primary/20 to-primary/5 flex items-center justify-center">
        <span className="text-6xl font-bold text-primary/20">{String(data.location ?? '').charAt(0).toUpperCase()}</span>
      </div>

      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">{String(data.location ?? 'Untitled')}</h1>

        </div>
        <Button variant={isEditing ? 'outline' : 'default'} onClick={() => {
          if (!isEditing) setEditForm({ table_number: data.table_number ?? '', capacity: data.capacity ?? '', location: data.location ?? '', status: data.status ?? '', created_by: data.created_by ?? '' })
          setIsEditing(!isEditing)
        }}>
          {isEditing ? <><X className="h-4 w-4 mr-2" />Cancel</> : <><Edit2 className="h-4 w-4 mr-2" />Edit</>}
        </Button>
      </div>



      {isEditing ? (
        <Card>
          <CardHeader><CardTitle>Edit Restaurant Table</CardTitle></CardHeader>
          <CardContent>
            <form className="space-y-4" onSubmit={e => { e.preventDefault(); updateRestaurantTables.mutate(editForm) }}>
              <div><label className="text-sm font-medium">Table Number</label><Input type="number" value={String(editForm.table_number ?? '')} onChange={e => setEditForm(p => ({ ...p, table_number: e.target.value }))} /></div>
              <div><label className="text-sm font-medium">Capacity</label><Input type="number" value={String(editForm.capacity ?? '')} onChange={e => setEditForm(p => ({ ...p, capacity: e.target.value }))} /></div>
              <div><label className="text-sm font-medium">Location</label><Input type="text" value={String(editForm.location ?? '')} onChange={e => setEditForm(p => ({ ...p, location: e.target.value }))} /></div>
              <div><label className="text-sm font-medium">Status</label><Input value={String(editForm.status ?? '')} onChange={e => setEditForm(p => ({ ...p, status: e.target.value }))} /></div>
              <div><label className="text-sm font-medium">Created By</label><Input type="text" value={String(editForm.created_by ?? '')} onChange={e => setEditForm(p => ({ ...p, created_by: e.target.value }))} /></div>
              <div className="flex gap-2">
                <Button type="submit" disabled={updateRestaurantTables.isPending}>
                  {updateRestaurantTables.isPending ? 'Saving...' : 'Save'}
                </Button>
                <Button type="button" variant="outline" onClick={() => setIsEditing(false)}>Cancel</Button>
              </div>
            </form>
          </CardContent>
        </Card>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="space-y-4">
            <h3 className="font-semibold text-lg border-b pb-2">Details</h3>
            <div>
              <p className="text-sm text-muted-foreground">Location</p>
              <p className="font-medium">{String(data.location ?? '—')}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Created By</p>
              <p className="font-medium">{String(data.created_by ?? '—')}</p>
            </div>
          </div>
          <div className="space-y-4">
            <h3 className="font-semibold text-lg border-b pb-2">Properties</h3>
            <div>
              <p className="text-sm text-muted-foreground">Table Number</p>
              <p className="font-medium">{String(data.table_number ?? '—')}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Capacity</p>
              <p className="font-medium">{String(data.capacity ?? '—')}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Status</p>
              <p className="font-medium">{String(data.status ?? '—')}</p>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
