// Auto-generated by VibeStack Design Engine v2 — CardGrid skill
import { useState } from 'react'
import { createFileRoute, Link } from '@tanstack/react-router'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { supabase } from '@/lib/supabase'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Plus, Trash2 } from 'lucide-react'

export const Route = createFileRoute('/_authenticated/restaurant-tables')({
  component: RestaurantTablesListPage,
})

function RestaurantTablesListPage() {
  const queryClient = useQueryClient()
  const [open, setOpen] = useState(false)
  const [form, setForm] = useState<Record<string, string | number | boolean>>({})

  const { data: items = [], isPending, error } = useQuery({
    queryKey: ['restaurant_tables'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('restaurant_tables')
        .select('*')
        .order('created_at', { ascending: false })
      if (error) throw error
      return data ?? []
    },
  })

  const createRestaurantTables = useMutation({
    mutationFn: async (values: Record<string, unknown>) => {
      const { error } = await supabase.from('restaurant_tables').insert(values)
      if (error) throw error
    },
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['restaurant_tables'] }); setOpen(false); setForm({}) },
  })

  const deleteRestaurantTables = useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase.from('restaurant_tables').delete().eq('id', id)
      if (error) throw error
    },
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['restaurant_tables'] }),
  })



  if (isPending) return <div className="flex justify-center py-20"><p className="text-muted-foreground">Loading restaurant tables...</p></div>
  if (error) return <div className="flex justify-center py-20"><p className="text-destructive">Error: {error.message}</p></div>

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-3xl font-bold tracking-tight">Restaurant Tables</h1>
        <Dialog open={open} onOpenChange={setOpen}>
          <DialogTrigger asChild>
            <Button><Plus className="mr-2 h-4 w-4" />New Restaurant Table</Button>
          </DialogTrigger>
          <DialogContent className="sm:max-w-[500px]">
            <DialogHeader>
              <DialogTitle>New Restaurant Table</DialogTitle>
              <DialogDescription className="sr-only">Create a new Restaurant Table</DialogDescription>
            </DialogHeader>
            <form className="space-y-4" onSubmit={e => { e.preventDefault(); createRestaurantTables.mutate(form) }}>
          <div>
            <label className="text-sm font-medium">Table Number</label>
            <Input type="number" value={String(form.table_number ?? '')} onChange={e => setForm(p => ({ ...p, table_number: e.target.value }))} placeholder="Enter table number" />
          </div>
          <div>
            <label className="text-sm font-medium">Capacity</label>
            <Input type="number" value={String(form.capacity ?? '')} onChange={e => setForm(p => ({ ...p, capacity: e.target.value }))} placeholder="Enter capacity" />
          </div>
          <div>
            <label className="text-sm font-medium">Location</label>
            <Input type="text" value={String(form.location ?? '')} onChange={e => setForm(p => ({ ...p, location: e.target.value }))} placeholder="Enter location" />
          </div>
          <div>
            <label className="text-sm font-medium">Status</label>
            <select className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" value={String(form.status ?? '')} onChange={e => setForm(p => ({ ...p, status: e.target.value }))}>
              <option value="">Select...</option>
              <option value="pending">pending</option>
              <option value="active">active</option>
              <option value="completed">completed</option>
            </select>
          </div>
          <div>
            <label className="text-sm font-medium">Created By</label>
            <Input type="text" value={String(form.created_by ?? '')} onChange={e => setForm(p => ({ ...p, created_by: e.target.value }))} placeholder="Enter created by" />
          </div>
              <Button type="submit" disabled={createRestaurantTables.isPending} className="w-full">
                {createRestaurantTables.isPending ? 'Creating...' : 'Create Restaurant Table'}
              </Button>
            </form>
          </DialogContent>
        </Dialog>
      </div>

      {items.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-20 text-center">
          <p className="text-muted-foreground mb-4">No restaurant tables yet. Create your first restaurant tables!</p>
          <Button onClick={() => setOpen(true)}><Plus className="mr-2 h-4 w-4" />Add your first restaurant table</Button>
        </div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {items.map((item: Record<string, unknown>) => (
            <Card key={String(item.id)} className="overflow-hidden hover:shadow-lg transition-shadow group">
              <div className="aspect-video bg-gradient-to-br from-primary/20 to-primary/5 flex items-center justify-center">
                <span className="text-4xl font-bold text-primary/30">{String(item.location ?? '').charAt(0).toUpperCase()}</span>
              </div>
              <CardHeader className="pb-2">
                <CardTitle className="text-lg line-clamp-2">
                  <Link to="/restaurant-tables/$id" params={{ id: String(item.id) }} className="hover:text-primary transition-colors">
                    {String(item.location ?? 'Untitled')}
                  </Link>
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-1">
              <p className="text-sm text-muted-foreground">{String(item.status ?? '—')}</p>
              <p className="text-sm text-muted-foreground">{String(item.table_number ?? '—')}</p>
              <p className="text-sm text-muted-foreground">{String(item.capacity ?? '—')}</p>
                <div className="pt-2 flex justify-end">
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={e => { e.preventDefault(); deleteRestaurantTables.mutate(String(item.id)) }}
                    className="text-destructive hover:text-destructive"
                  >
                    <Trash2 className="h-4 w-4" />
                  </Button>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  )
}
