// Auto-generated by VibeStack — do not edit manually
import { Link, Outlet } from '@tanstack/react-router'

const navLinks = [
  { to: '/menu-categories', label: 'Menu Categories' },
  { to: '/menu-items', label: 'Menu Items' },
  { to: '/restaurant-tables', label: 'Restaurant Tables' },
  { to: '/reservations', label: 'Reservations' },
  { to: '/orders', label: 'Orders' },
  { to: '/order-items', label: 'Order Items' },
]

export function AppLayout() {
  return (
    <div className="min-h-screen bg-background">
      <header className="sticky top-0 z-50 border-b bg-card/80 backdrop-blur-md">
        <nav className="container mx-auto flex items-center gap-1 px-4 py-3">
          {/* Brand mark */}
          <Link to="/" className="mr-6 flex items-center gap-2.5 shrink-0">
            <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-primary text-xs font-bold text-primary-foreground shadow-sm">
              L
            </span>
            <span className="text-sm font-semibold tracking-tight">La Piazza Manager</span>
          </Link>

          {/* Nav links */}
          {navLinks.map((link) => (
            <Link
              key={link.to}
              to={link.to}
              className="rounded-md px-3 py-1.5 text-sm text-muted-foreground transition-colors hover:bg-muted hover:text-foreground"
              activeProps={{ className: 'rounded-md px-3 py-1.5 text-sm bg-muted text-foreground font-medium' }}
            >
              {link.label}
            </Link>
          ))}
          
        </nav>
        {/* Accent line */}
        <div className="h-px bg-gradient-to-r from-transparent via-primary/40 to-transparent" />
      </header>

      <main className="container mx-auto px-4 py-8">
        <Outlet />
      </main>
    </div>
  )
}
