/* eslint-disable */
// @ts-nocheck
// This file is auto-generated by VibeStack — do not edit manually

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticatedImport } from './routes/_authenticated/route'
import { Route as MenuCategoriesListImport } from './routes/_authenticated/menu-categories'
import { Route as MenuCategoriesDetailImport } from './routes/_authenticated/menu-categories.$id'
import { Route as MenuItemsListImport } from './routes/_authenticated/menu-items'
import { Route as MenuItemsDetailImport } from './routes/_authenticated/menu-items.$id'
import { Route as RestaurantTablesListImport } from './routes/_authenticated/restaurant-tables'
import { Route as RestaurantTablesDetailImport } from './routes/_authenticated/restaurant-tables.$id'
import { Route as ReservationsListImport } from './routes/_authenticated/reservations'
import { Route as ReservationsDetailImport } from './routes/_authenticated/reservations.$id'
import { Route as OrdersListImport } from './routes/_authenticated/orders'
import { Route as OrdersDetailImport } from './routes/_authenticated/orders.$id'
import { Route as OrderItemsListImport } from './routes/_authenticated/order-items'
import { Route as OrderItemsDetailImport } from './routes/_authenticated/order-items.$id'

const IndexRoute = IndexImport.update({ id: '/', path: '/', getParentRoute: () => rootRoute } as any)
const AuthenticatedRoute = AuthenticatedImport.update({ id: '/_authenticated', getParentRoute: () => rootRoute } as any)

const MenuCategoriesListRoute = MenuCategoriesListImport.update({ path: '/menu-categories', getParentRoute: () => AuthenticatedRoute } as any)
const MenuCategoriesDetailRoute = MenuCategoriesDetailImport.update({ path: '/menu-categories/$id', getParentRoute: () => AuthenticatedRoute } as any)
const MenuItemsListRoute = MenuItemsListImport.update({ path: '/menu-items', getParentRoute: () => AuthenticatedRoute } as any)
const MenuItemsDetailRoute = MenuItemsDetailImport.update({ path: '/menu-items/$id', getParentRoute: () => AuthenticatedRoute } as any)
const RestaurantTablesListRoute = RestaurantTablesListImport.update({ path: '/restaurant-tables', getParentRoute: () => AuthenticatedRoute } as any)
const RestaurantTablesDetailRoute = RestaurantTablesDetailImport.update({ path: '/restaurant-tables/$id', getParentRoute: () => AuthenticatedRoute } as any)
const ReservationsListRoute = ReservationsListImport.update({ path: '/reservations', getParentRoute: () => AuthenticatedRoute } as any)
const ReservationsDetailRoute = ReservationsDetailImport.update({ path: '/reservations/$id', getParentRoute: () => AuthenticatedRoute } as any)
const OrdersListRoute = OrdersListImport.update({ path: '/orders', getParentRoute: () => AuthenticatedRoute } as any)
const OrdersDetailRoute = OrdersDetailImport.update({ path: '/orders/$id', getParentRoute: () => AuthenticatedRoute } as any)
const OrderItemsListRoute = OrderItemsListImport.update({ path: '/order-items', getParentRoute: () => AuthenticatedRoute } as any)
const OrderItemsDetailRoute = OrderItemsDetailImport.update({ path: '/order-items/$id', getParentRoute: () => AuthenticatedRoute } as any)

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthenticatedRoute.addChildren([
    MenuCategoriesListRoute,
    MenuCategoriesDetailRoute,
    MenuItemsListRoute,
    MenuItemsDetailRoute,
    RestaurantTablesListRoute,
    RestaurantTablesDetailRoute,
    ReservationsListRoute,
    ReservationsDetailRoute,
    OrdersListRoute,
    OrdersDetailRoute,
    OrderItemsListRoute,
    OrderItemsDetailRoute,
  ]),
])
